let dark1 = document.getElementById("dark");
function dark(){
        var wrapper1 = document.getElementById("wrapper");
        wrapper1.classList.remove("wrapper");
        wrapper1.classList.add("wrapper-dark");
        var title1 = document.getElementById("title");
        title1.classList.remove("title");
        title1.classList.add("title-dark");
        let field1 = document.getElementById("field");
        field1.classList.remove("field");
        field1.classList.add("field-dark");
        let field2 = document.getElementById("field1");
        field2.classList.remove("field");
        field2.classList.add("field-dark");
        let field3 = document.getElementById("field2");
        field3.classList.remove("field");
        field3.classList.add("field-dark");
        let field4 = document.getElementById("field3");
        field4.classList.remove("field");
        field4.classList.add("field-dark");
        let field5 = document.getElementById("field4");
        field5.classList.remove("field");
        field5.classList.add("field-dark");
        let signup1 = document.getElementById("signup");
        signup1.classList.remove("signup");
        signup1.classList.add("signup-dark");
        let toggle1 = document.getElementById("toggle");
        toggle1.classList.remove("toggle");
        toggle1.classList.add("toggle-dark");
        let tLabel1 = document.getElementById("tLabel");
        tLabel1.classList.remove("tLabe");
        tLabel1.classList.add("tLabe-dark");
        let check1 = document.getElementById("check");
        tLabel1.classList.remove("tLabe");
        tLabel1.classList.add("tLabe-dark");
        let container1 = document.getElementById("container");
        container1.classList.remove("container");
        container1.classList.add("container-dark"); 
}
function light(){
    var wrapper1 = document.getElementById("wrapper");
    wrapper1.classList.remove("wrapper-dark");
    wrapper1.classList.add("wrapper");
    var title1 = document.getElementById("title");
    title1.classList.remove("title-dark");
    title1.classList.add("title");
    let field1 = document.getElementById("field");
    field1.classList.remove("field-dark");
    field1.classList.add("field");
    let field2 = document.getElementById("field1");
    field2.classList.remove("field-dark");
    field2.classList.add("field");
    let field3 = document.getElementById("field2");
    field3.classList.remove("field-dark");
    field3.classList.add("field");
    let field4 = document.getElementById("field3");
    field4.classList.remove("field-dark");
    field4.classList.add("field");
    let field5 = document.getElementById("field4");
    field5.classList.remove("field-dark");
    field5.classList.add("field");
    let signup1 = document.getElementById("signup");
    signup1.classList.remove("signup-dark");
    signup1.classList.add("signup");
    let toggle1 = document.getElementById("toggle");
    toggle1.classList.remove("toggle-dark");
    toggle1.classList.add("toggle");
    let tLabel1 = document.getElementById("tLabel");
    tLabel1.classList.remove("tLabe-dark");
    tLabel1.classList.add("tLabe");
    let check1 = document.getElementById("check");
    tLabel1.classList.remove("tLabe-dark");
    tLabel1.classList.add("tLabe");
    let container1 = document.getElementById("container");
    container1.classList.remove("container-dark");
    container1.classList.add("container");
}